version: "3.1"
services:

  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: office

  app:
    image: imixs/imixs-documents
    depends_on:
      - db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://db/office"      
      TZ: "Europe/Berlin"
    ports:
      - "9080:9080"
      - "9443:9443"
      - "7777:7777"
#    volumes:
#      - ~/git/imixs-jsf-example/src/docker/deployments:/config/dropins/   



    
#  imixsadmin:
#    image: imixs/imixs-admin
#    ports:
#      - "8888:8