version: "3.1"
services:

  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: office

  app:
    image: imixs/imixs-documents
    depends_on:
      - db
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://db/office"      
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    volumes:
        - ~/git/imixs-documents/src/docker/deployments:/opt/wildfly/standalone/deployments/

  imixsadmin:
    image: imixs/imixs-admin
    ports:
      - "8888:8080"
 