---
###################################################
# Persistence Volume for DB
###################################################
kind: PersistentVolume
apiVersion: v1
metadata:
  name: dbdata-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: dbdata-pvc
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: imixs-documents
  storageClassName: longhorn-durable



---
###################################################
# Persistence Volume Claim for DB
###################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-durable
  resources:
    requests:
      storage: 2Gi
  volumeName: "dbdata-pv"




---
###################################################
# Persistence Volume Claim for Appdata
###################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdata
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi

