version: "3.6"
services:

#######################
# PostgreSQL
#######################
  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: office
    volumes: 
      - dbdata:/var/lib/postgresql/data

#######################
# Imixs-Documents
#######################
  imixs-documents:
    image: imixs/imixs-documents:latest
    depends_on:
      - db
    environment:
      JAVA_OPTS: "-Dnashorn.args=--no-deprecation-warning"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://db/office"      
      TZ: "Europe/Berlin"
      LANG: "en_US.UTF-8"
      MAILGATEWAY: "localhost"
      ASYNCEVENT_PROCESSOR_ENABLED: "true"
      ASYNCEVENT_PROCESSOR_INITIALDELAY: "10000"
      OCR_SERVICE_ENDPOINT: "http://tika:9998/tika"
      OCR_SERVICE_MODE: "MODEL"
      #OCR_STRATEGY: "NO_OCR, OCR_ONLY, OCR_AND_TEXT_EXTRACTION, AUTO (default)" 
      OCR_STRATEGY: "AUTO"
      ML_SERVICE_ENDPOINT: "http://imixs-ml-spacy:8000/"
      ML_MODEL: "invoice-de-0.1.0"
      # Enable Training Scheduler
      ML_TRAINING_SCHEDULER_ENABLED: "true"
      ML_TRAINING_SCHEDULER_INTERVAL: "10000"
      ML_TRAINING_SCHEDULER_INITIALDELAY: "60000" 

     # Signature
      SIGNATURE_SERVICE_ENDPOINT: "http://imixssignature:8080/api"

      # Collabora integration
      WOPI_PUBLIC_ENDPOINT: "http://localhost:9980"
      WOPI_DISCOVERY_ENDPOINT: "http://libreoffice-app:9980/hosting/discovery"
      WOPI_HOST_ENDPOINT: "http://imixs-documents:8080/api/wopi/"
      WOPI_TEMPLATES: "/wopi/templates"

    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    volumes:
      # openliberty
      # - ./deployments:/config/dropins/ 
      - ./deployments:/opt/jboss/wildfly/standalone/deployments/
      - ./deployments/office-templates/:/wopi/templates/


#######################
# Libre Office Online
#######################
  libreoffice-app:
    image: collabora/code:6.4.9.2
    container_name: libreoffice-app
    expose:
      - 9980
    ports:
      - "9980:9980"
    environment:
      - username=admin
      - password=adminadmin
    volumes:
      - ./configuration/collabora/loolwsd.xml:/etc/loolwsd/loolwsd.xml


volumes:
  dbdata: 