version: "3.6"
services:

  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: office
    volumes: 
      - dbdata:/var/lib/postgresql/data

  imixs-documents:
    image: imixs/imixs-documents:latest
    depends_on:
      - db
    environment:
      JAVA_OPTS: "-Dnashorn.args=--no-deprecation-warning"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://db/office"      
      TZ: "Europe/Berlin"
      LANG: "en_US.UTF-8"
      MAILGATEWAY: "localhost"
      ASYNCEVENT_PROCESSOR_ENABLED: "true"
      ASYNCEVENT_PROCESSOR_INITIALDELAY: "10000"
      OCR_SERVICE_ENDPOINT: "http://tika:9998/tika"
      OCR_SERVICE_MODE: "MODEL"
      #OCR_PDF_MODE: "OCR_ONLY | TEXT_ONLY | TEXT_AND_OCR (default)" 
      OCR_PDF_MODE: "TEXT_AND_OCR"
      ML_SERVICE_ENDPOINT: "http://imixs-ml-spacy:8000/"
      ML_MODEL: "invoice-de-0.1.0"
      # Enable Training Scheduler
      ML_TRAINING_SCHEDULER_ENABLED: "true"
      ML_TRAINING_SCHEDULER_INTERVAL: "10000"
      ML_TRAINING_SCHEDULER_INITIALDELAY: "60000" 
    ports:
      - "8080:8080"


# Tika OCR Service
  tika: 
    #image: imixs/tika
    image: apache/tika:1.24.1-full
    environment:
      TZ: "Europe/Berlin"
    ports:
      - "9998:9998"  


# Imixs-ML-spaCy Service
  imixs-ml-spacy: 
    image: imixs/imixs-ml-spacy:latest
    environment:
      PYTHONUNBUFFERED: 1
      TZ: "Europe/Berlin"
      MODEL_LANGUAGE: "de"
      MODEL_PATH: "models/" 

    ports:
      - "8000:8000"  
    #volumes:
    #  - ../src/models/:/usr/src/app/models/


volumes:
  dbdata: 