version: "3.6"
services:

  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: office
    volumes: 
      - dbdata:/var/lib/postgresql/data

  imixs-documents:
    image: imixs/imixs-documents
    depends_on:
      - db
    environment:
      JAVA_OPTS: "-Dnashorn.args=--no-deprecation-warning"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://db/office"      
      TZ: "Europe/Berlin"
      MAILGATEWAY: "localhost"
    ports:
      - "8080:8080"
 

volumes:
  dbdata: 