---
###################################################
# Persistence Volume Claim for DB
# using the default storageClassName
###################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imixs-documents-dbdata
spec:
  accessModes:
    - ReadWriteOnce
#  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi


---
###################################################
# Persistence Volume Claim for Appdata
# using the default storageClassName
###################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imixs-documents-appdata
spec:
  accessModes:
    - ReadWriteOnce
#  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi

