---
###################################################
# Service db
###################################################
apiVersion: v1
kind: Service
metadata:
  name: db
  labels: 
    app: db
spec:
  clusterIP: None
  ports:
    - name: tcp
      port: 5432
  selector:
    app: db


---
###################################################
# Service imixs-documents
###################################################
apiVersion: v1
kind: Service
metadata:
  name: imixs-documents
  labels: 
    app: imixs-documents
spec:
  clusterIP: None
  ports:
  - name: web
    port: 8080
  selector:
    app: imixs-documents





