---
###################################################
# Service db 
#   - running with ClusterIP=None
###################################################
apiVersion: v1
kind: Service
metadata:
  name: db
  labels: 
    app: postgres
spec:
  clusterIP: None
  ports:
    - name: tcp
      port: 5432
  selector:
    app: postgres


---
###################################################
# Service imixs-documents
###################################################
apiVersion: v1
kind: Service
metadata:
  name: imixs-documents
  labels: 
    app: imixs-documents
spec:
  ports:
  - name: web
    port: 8080
  - name: admin
    port: 9990
  selector:
    app: imixs-documents





